# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Fire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fire
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  target 'FireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireUITests' do
    # Pods for testing
  end

end
